name: /data/home/lprakas/clear/envs/selenium_environment
channels:
  - conda-forge
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - attrs=25.3.0
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.4.1
  - exceptiongroup=1.2.2
  - h11=0.14.0
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - outcome=1.3.0.post0
  - pip=25.0
  - python=3.10.16
  - python_abi=3.10
  - readline=8.2
  - requests=2.32.3
  - selenium=4.11.2
  - setuptools=75.8.0
  - sniffio=1.3.1
  - sortedcontainers=2.4.0
  - sqlite=3.45.3
  - tk=8.6.14
  - trio=0.30.0
  - trio-websocket=0.12.2
  - typing_extensions=4.13.2
  - tzdata=2025a
  - wheel=0.45.1
  - wsproto=1.2.0
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - idna==3.10
      - urllib3==2.4.0
